export const ACTION_ON_NEW_NOTIFICATION = 'NEW_NOTIFICATION';
export const ACTION_SET_NOTIFICATION_COUNT = 'SET_NOTIFICATION_COUNT';
export const ACTION_RESET_REDUX_NOTIFICATION_STATE = 'RESET_REDUX_NOTIFICATION_STATE';